language: android
dist: trusty
android:
  components:
  - tools
  - platform-tools
  licenses:
  - 'android-sdk-license-.+'
  - '.+'
git:
  depth: false
install: true
before_install:
- openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out ~/secrets.tar -d
- tar xvf ~/secrets.tar
- yes | sdkmanager "platforms;android-30"
- chmod +x ./gradlew
- chmod +x ./scripts/script.sh
script:
- "./scripts/script.sh"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
env:
  global:
  - ADB_INSTALL_TIMEOUT=8
  - ANDROID_API_LEVEL=28
  - ANDROID_BUILD_TOOLS_VERSION=28.0.3
